# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Define target output
target: prom

# Define TOP_DIR
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include $(TOP_DIR)/targets/shared_config.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
